name: Build POI

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  build-poi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build pois
        run: npm run build-pois
      - name: Generate readme
        run: npm run generate-readme
      - name: Commit updated pois
        run: |-
          git config user.name "TrailDbBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -F log.txt || exit 0
          git push