name: Daily Update

on:
  workflow_dispatch:
  schedule:
    - cron: "1 2 * * *"

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run trails update
        run: npm run update-trails
      - name: Commit updated trails
        run: |-
          git config user.name "TrailDbBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -F log.txt || exit 0
          git push
      - name: Build trails
        run: npm run build-trails
      - name: Generate readme
        run: npm run generate-readme
      - name: Commit built trails
        run: |-
          git config user.name "TrailDbBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -F log.txt || exit 0
          git push
      - name: Run poi update
        run: npm run update-pois
      - name: Commit updated pois
        run: |-
          git config user.name "TrailDbBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -F log.txt || exit 0
          git push
      - name: Build pois
        run: npm run build-pois
      - name: Generate readme
        run: npm run generate-readme
      - name: Commit built pois
        run: |-
          git config user.name "TrailDbBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -F log.txt || exit 0
          git push
